-- 40_ctd.sql — the CTD archive in PostgreSQL: originals immutable, flags beside, products on top.
--   docker exec -i postgis psql -U admin -d calcofi -v ON_ERROR_STOP=1 -f /share/github/CalCOFI/server/postgis/init/40_ctd.sql
-- Idempotent (CREATE IF NOT EXISTS / OR REPLACE). Run as superuser; objects are owned by calcofi_admin.
--
-- Design (plan 2026-08-17 WS8, decisions D7/D8):
--   ctd.file         one row per source file (archive member), sha256, stage, cruise — IMMUTABLE
--   ctd.scan         one row per scan line, EVERY source column verbatim (82 columns of the
--                    calcofi.org db-CSV products, lower-cased), + file_id/row_num provenance — IMMUTABLE
--   ctd.scan_column  what each column is (source header, description, units) — the data dictionary
--   ctd.qual_code    the flag vocabulary used in ctd.flag (IODE/SeaDataNet primary flags 0–9);
--   ctd.source_qual_code  the source's own *Q column codes (0,1,2,8,9), for reference
--   ctd.flag         the ledger: (scan|file) × variable × proposal; status proposed→accepted|rejected|withdrawn;
--                    row-level security (propose = anyone, review = curators), audit-trailed
--   ctd.flag_audit   append-only copy of every change to ctd.flag
--   ctd.cast         MATERIALIZED: one row per physical cast per file, from the header columns
--   ctd.v_scan_best  scans of the best data stage per cruise (final > prelim_with_bottle > prelim_without_bottle)
--   ctd.v_scan_qc    v_scan_best + <var>_qc / <var>_fix columns from ACCEPTED flags (generated by ctd.build_qc_views())
--   ctd.v_scan_clean v_scan_best with accepted-bad -> NULL and accepted-fix substituted
--   ctd.refresh_derived()  REFRESH the materialized products after a load
--
-- Immutability: calcofi_loader may INSERT into file/scan; nobody UPDATEs/DELETEs them — a trigger
-- raises unless `SET ctd.allow_mutation = on` (a deliberate, logged admin act). Fixes are flags.

SET ROLE calcofi_admin;

-- ── reference: data dictionary for the scan columns ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ctd.scan_column (
  column_name    text PRIMARY KEY,        -- as in ctd.scan
  source_header  text NOT NULL UNIQUE,    -- exact header text in the db-CSV files
  ordinal        smallint NOT NULL,
  kind           text NOT NULL CHECK (kind IN ('key','measurement','qual','bottle')),
  qual_column    text REFERENCES ctd.scan_column(column_name),  -- the *Q column that grades this one
  description    text,
  units          text,
  measurement_type text                   -- workflows metadata/measurement_type.csv name, when mapped
);
COMMENT ON TABLE ctd.scan_column IS 'Data dictionary for ctd.scan: every column, its exact source header, what grades it, units.';


-- the 82 columns of the db-CSV products (header text verbatim in source_header). Qual columns
-- first so the measurement rows can reference them. Descriptions/units are filled by the loader
-- from workflows/metadata/measurement_type.csv (_source_column).
INSERT INTO ctd.scan_column (column_name, source_header, ordinal, kind, qual_column) VALUES
  ('prq','PrQ',15,'qual',NULL),
  ('temp1q','Temp1Q',17,'qual',NULL),
  ('temp2q','Temp2Q',19,'qual',NULL),
  ('salt1q','Salt1Q',22,'qual',NULL),
  ('salt2q','Salt2Q',25,'qual',NULL),
  ('ox1q','Ox1Q',29,'qual',NULL),
  ('ox2q','Ox2Q',33,'qual',NULL),
  ('fluorq','FluorQ',45,'qual',NULL),
  ('isusq','ISUSQ',49,'qual',NULL),
  ('sigthetats1q','SigThetaTS1Q',53,'qual',NULL),
  ('sigthetats2q','SigThetaTS2Q',55,'qual',NULL),
  ('transq','TransQ',58,'qual',NULL),
  ('phq','pHQ',60,'qual',NULL),
  ('sparq','SPARQ',62,'qual',NULL),
  ('parq','PARQ',64,'qual',NULL)
ON CONFLICT (column_name) DO NOTHING;
INSERT INTO ctd.scan_column (column_name, source_header, ordinal, kind, qual_column) VALUES
  ('project','Project',1,'key',NULL),
  ('study','Study',2,'key',NULL),
  ('ord_occ','Ord_Occ',3,'key',NULL),
  ('event_num','Event_Num',4,'key',NULL),
  ('cast_id','Cast_ID',5,'key',NULL),
  ('date_time_utc','Date_Time_UTC',6,'key',NULL),
  ('date_time_pst','Date_Time_PST',7,'key',NULL),
  ('lat_dec','Lat_Dec',8,'key',NULL),
  ('lon_dec','Lon_Dec',9,'key',NULL),
  ('sta_id','Sta_ID',10,'key',NULL),
  ('line','Line',11,'key',NULL),
  ('sta','Sta',12,'key',NULL),
  ('depth','Depth',13,'key',NULL),
  ('pressure','Pressure',14,'measurement','prq'),
  ('temp1','Temp1',16,'measurement','temp1q'),
  ('temp2','Temp2',18,'measurement','temp2q'),
  ('tempave','TempAve',20,'measurement',NULL),
  ('salt1','Salt1',21,'measurement','salt1q'),
  ('salt1_corr','Salt1_Corr',23,'measurement','salt1q'),
  ('salt2','Salt2',24,'measurement','salt2q'),
  ('salt2_corr','Salt2_Corr',26,'measurement','salt2q'),
  ('saltave_corr','SaltAve_Corr',27,'measurement',NULL),
  ('ox1','Ox1',28,'measurement','ox1q'),
  ('ox1_cruisecorr','Ox1_CruiseCorr',30,'measurement','ox1q'),
  ('ox1_stacorr','Ox1_StaCorr',31,'measurement','ox1q'),
  ('ox2','Ox2',32,'measurement','ox2q'),
  ('ox2_cruisecorr','Ox2_CruiseCorr',34,'measurement','ox2q'),
  ('ox2_stacorr','Ox2_StaCorr',35,'measurement','ox2q'),
  ('oxave_stacorr','OxAve_StaCorr',36,'measurement',NULL),
  ('ox1um','Ox1uM',37,'measurement','ox1q'),
  ('ox1um_cruisecorr','Ox1uM_CruiseCorr',38,'measurement','ox1q'),
  ('ox1um_stacorr','Ox1uM_StaCorr',39,'measurement','ox1q'),
  ('ox2um','Ox2uM',40,'measurement','ox2q'),
  ('ox2um_cruisecorr','Ox2uM_CruiseCorr',41,'measurement','ox2q'),
  ('ox2um_stacorr','Ox2uM_StaCorr',42,'measurement','ox2q'),
  ('oxaveum_stacorr','OxAveuM_StaCorr',43,'measurement',NULL),
  ('fluorv','FluorV',44,'measurement','fluorq'),
  ('estchl_cruisecorr','EstChl_CruiseCorr',46,'measurement','fluorq'),
  ('estchl_stacorr','EstChl_StaCorr',47,'measurement','fluorq'),
  ('isusv','ISUSV',48,'measurement','isusq'),
  ('estno3_cruisecorr','EstNO3_CruiseCorr',50,'measurement','isusq'),
  ('estno3_stacorr','EstNO3_StaCorr',51,'measurement','isusq'),
  ('sigthetats1','SigThetaTS1',52,'measurement','sigthetats1q'),
  ('sigthetats2','SigThetaTS2',54,'measurement','sigthetats2q'),
  ('bat','BAT',56,'measurement','transq'),
  ('xmiss','XMiss',57,'measurement','transq'),
  ('ph','pH',59,'measurement','phq'),
  ('spar','SPAR',61,'measurement','sparq'),
  ('par','PAR',63,'measurement','parq'),
  ('pot1','PoT1',65,'measurement',NULL),
  ('pot2','PoT2',66,'measurement',NULL),
  ('dynht','DynHt',67,'measurement',NULL),
  ('sva','SVA',68,'measurement',NULL),
  ('oxsat1','OxSat1',69,'measurement',NULL),
  ('oxsat2','OxSat2',70,'measurement',NULL),
  ('btl_depth','BTL_Depth',71,'bottle',NULL),
  ('btl_temp','BTL_Temp',72,'bottle',NULL),
  ('saltb','SaltB',73,'bottle',NULL),
  ('oxb','OxB',74,'bottle',NULL),
  ('oxbum','OxBuM',75,'bottle',NULL),
  ('chl_a','Chl-a',76,'bottle',NULL),
  ('phaeo','Phaeo',77,'bottle',NULL),
  ('no3','NO3',78,'bottle',NULL),
  ('no2','NO2',79,'bottle',NULL),
  ('nh4','NH4',80,'bottle',NULL),
  ('po4','PO4',81,'bottle',NULL),
  ('sil','SIL',82,'bottle',NULL)
ON CONFLICT (column_name) DO NOTHING;

-- ── ctd.file ────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ctd.file (
  file_id       int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  archive       text NOT NULL,            -- zip name, e.g. 19-9709NH_CTDFinalDB.zip
  path          text NOT NULL,            -- member path inside the zip
  study         text NOT NULL,            -- source cruise id as in the files, e.g. 9709NH
  cruise_key    text,                     -- integrated-db key (YYYY-MM-NODC) via the release cruise table; NULL if unmapped
  data_stage    text NOT NULL CHECK (data_stage IN ('final','preliminary_with_bottle','preliminary_without_bottle')),
  cast_dir      char(1) NOT NULL CHECK (cast_dir IN ('D','U')),
  is_best_stage boolean NOT NULL DEFAULT false,  -- best stage available for this study (final > prelim+btl > prelim)
  sha256        text NOT NULL UNIQUE,
  n_bytes       bigint NOT NULL,
  n_rows        int,
  gcs_uri       text,                     -- where the archive lives off-box
  loaded_at     timestamptz NOT NULL DEFAULT now(),
  loaded_by     text NOT NULL DEFAULT current_user,
  UNIQUE (archive, path)
);
COMMENT ON TABLE ctd.file IS 'One row per source file of the CTD archive (immutable; a re-load of a changed file is a new row with a new sha256).';
CREATE INDEX IF NOT EXISTS file_study_idx ON ctd.file (study, data_stage, cast_dir);

-- ── ctd.scan — the 82 db-CSV columns, verbatim ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ctd.scan (
  scan_id       bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  file_id       int NOT NULL REFERENCES ctd.file(file_id),
  row_num       int NOT NULL,             -- 1-based data line within the file (header = 0)
  -- keys / header columns
  project text, study text, ord_occ text, event_num text, cast_id text,
  date_time_utc timestamp, date_time_pst timestamp,
  lat_dec double precision, lon_dec double precision,
  sta_id text, line double precision, sta double precision,
  depth double precision, pressure double precision, prq smallint,
  -- temperature
  temp1 double precision, temp1q smallint, temp2 double precision, temp2q smallint, tempave double precision,
  -- salinity
  salt1 double precision, salt1q smallint, salt1_corr double precision,
  salt2 double precision, salt2q smallint, salt2_corr double precision, saltave_corr double precision,
  -- oxygen (mL/L)
  ox1 double precision, ox1q smallint, ox1_cruisecorr double precision, ox1_stacorr double precision,
  ox2 double precision, ox2q smallint, ox2_cruisecorr double precision, ox2_stacorr double precision,
  oxave_stacorr double precision,
  -- oxygen (umol/kg)
  ox1um double precision, ox1um_cruisecorr double precision, ox1um_stacorr double precision,
  ox2um double precision, ox2um_cruisecorr double precision, ox2um_stacorr double precision,
  oxaveum_stacorr double precision,
  -- fluorescence / chl, nitrate (ISUS), density, transmissometer, pH, PAR
  fluorv double precision, fluorq smallint, estchl_cruisecorr double precision, estchl_stacorr double precision,
  isusv double precision, isusq smallint, estno3_cruisecorr double precision, estno3_stacorr double precision,
  sigthetats1 double precision, sigthetats1q smallint, sigthetats2 double precision, sigthetats2q smallint,
  bat double precision, xmiss double precision, transq smallint,
  ph double precision, phq smallint,
  spar double precision, sparq smallint, par double precision, parq smallint,
  -- derived physics
  pot1 double precision, pot2 double precision, dynht double precision, sva double precision,
  oxsat1 double precision, oxsat2 double precision,
  -- bottle values merged onto the scan
  btl_depth double precision, btl_temp double precision, saltb double precision, oxb double precision, oxbum double precision,
  chl_a double precision, phaeo double precision, no3 double precision, no2 double precision, nh4 double precision,
  po4 double precision, sil double precision,
  UNIQUE (file_id, row_num)
);
COMMENT ON TABLE ctd.scan IS 'Every scan line of every db-CSV cast file, every column verbatim (lower-cased names; see ctd.scan_column). Immutable: problems are rows in ctd.flag.';
CREATE INDEX IF NOT EXISTS scan_file_cast_depth_idx ON ctd.scan (file_id, cast_id, depth);
CREATE INDEX IF NOT EXISTS scan_study_idx ON ctd.scan (study);

-- ── immutability guard (file, scan) ─────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION ctd.no_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF coalesce(current_setting('ctd.allow_mutation', true), 'off') <> 'on' THEN
    RAISE EXCEPTION 'ctd.% is immutable (originals are never edited — record a flag in ctd.flag). Admins: SET ctd.allow_mutation = on; to override deliberately.', TG_TABLE_NAME
      USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS file_immutable ON ctd.file;
CREATE TRIGGER file_immutable BEFORE UPDATE OR DELETE ON ctd.file FOR EACH ROW EXECUTE FUNCTION ctd.no_mutation();
DROP TRIGGER IF EXISTS scan_immutable ON ctd.scan;
CREATE TRIGGER scan_immutable BEFORE UPDATE OR DELETE ON ctd.scan FOR EACH ROW EXECUTE FUNCTION ctd.no_mutation();
DROP TRIGGER IF EXISTS file_no_truncate ON ctd.file;
CREATE TRIGGER file_no_truncate BEFORE TRUNCATE ON ctd.file FOR EACH STATEMENT EXECUTE FUNCTION ctd.no_mutation();
DROP TRIGGER IF EXISTS scan_no_truncate ON ctd.scan;
CREATE TRIGGER scan_no_truncate BEFORE TRUNCATE ON ctd.scan FOR EACH STATEMENT EXECUTE FUNCTION ctd.no_mutation();

-- ── flag vocabularies ───────────────────────────────────────────────────────────────────────
-- The ledger uses the IODE / SeaDataNet primary-level flags — international, one digit, and
-- distinct from the source's own *Q codes (kept verbatim in ctd.scan and listed below).
CREATE TABLE IF NOT EXISTS ctd.qual_code (
  qual_code   smallint PRIMARY KEY,
  label       text NOT NULL,
  description text NOT NULL,
  is_bad      boolean NOT NULL,   -- when ACCEPTED, v_scan_clean nulls the value (unless a fix is given)
  iode_url    text DEFAULT 'https://vocab.nerc.ac.uk/collection/L20/current/'
);
INSERT INTO ctd.qual_code (qual_code, label, description, is_bad) VALUES
  (0, 'no_qc',           'No quality control performed',                                  false),
  (1, 'good',            'Good value',                                                    false),
  (2, 'probably_good',   'Probably good value',                                           false),
  (3, 'probably_bad',    'Probably bad value (potentially correctable)',                  true),
  (4, 'bad',             'Bad value',                                                     true),
  (5, 'changed',         'Value changed — proposed_value holds the corrected value',      false),
  (6, 'below_detection', 'Value below detection limit',                                   false),
  (7, 'in_excess',       'Value in excess of the sensor/method range',                    true),
  (8, 'interpolated',    'Interpolated value',                                            false),
  (9, 'missing',         'Missing value (e.g. a -99 sentinel served as data)',            true)
ON CONFLICT (qual_code) DO NOTHING;
COMMENT ON TABLE ctd.qual_code IS 'Flag vocabulary for ctd.flag: IODE/SeaDataNet primary-level flags (NERC L20). is_bad drives ctd.v_scan_clean.';

CREATE TABLE IF NOT EXISTS ctd.source_qual_code (
  code        smallint PRIMARY KEY,
  label       text NOT NULL,
  description text NOT NULL
);
INSERT INTO ctd.source_qual_code VALUES
  (0, 'good',          'Sensors operating normally (blank and 0 are the same statement)'),
  (1, 'use_primary',   'USE PRIMARY SENSOR — a sensor-selection instruction for a dual-sensor pair, not a grade'),
  (2, 'use_secondary', 'USE SECONDARY SENSOR — the primary is questionable (failure, bio-fouling of the pump)'),
  (8, 'questionable',  'Data questionable; sensor performing poorly'),
  (9, 'bad_or_missing','Bad OR missing sensor data (a row flagged 9 that still carries a number is bad data)')
ON CONFLICT (code) DO NOTHING;
COMMENT ON TABLE ctd.source_qual_code IS 'The source files'' own *Q column codes (CalCOFI CTD-CSV-Format.pdf / CTD Data Files.pdf), for reference; they live verbatim in ctd.scan.';

-- ── ctd.flag — the ledger ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ctd.flag (
  flag_id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  scan_id        bigint REFERENCES ctd.scan(scan_id),       -- NULL => file/cast-level flag
  file_id        int    REFERENCES ctd.file(file_id),       -- required when scan_id is NULL
  variable       text   NOT NULL,                           -- a ctd.scan column name, or '*' for the whole row/file
  qual_code      smallint NOT NULL REFERENCES ctd.qual_code(qual_code),
  proposed_value double precision,                          -- the corrected value (qual_code 5), else NULL
  rule_key       text,                                      -- set when a QC rule proposed it (workflows metadata/qc_rules)
  reason         text,
  status         text NOT NULL DEFAULT 'proposed' CHECK (status IN ('proposed','accepted','rejected','withdrawn')),
  created_by     text NOT NULL DEFAULT current_user,
  created_at     timestamptz NOT NULL DEFAULT now(),
  reviewed_by    text,
  reviewed_at    timestamptz,
  review_note    text,
  CHECK (scan_id IS NOT NULL OR file_id IS NOT NULL)   -- variable validity is enforced by ctd.flag_guard()
);
COMMENT ON TABLE ctd.flag IS 'QA/QC ledger: one row per (scan or file) × variable × proposal. Anyone proposes; curators accept/reject; history in ctd.flag_audit.';
CREATE INDEX IF NOT EXISTS flag_scan_idx   ON ctd.flag (scan_id, variable) WHERE scan_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS flag_file_idx   ON ctd.flag (file_id) WHERE file_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS flag_status_idx ON ctd.flag (status);
CREATE UNIQUE INDEX IF NOT EXISTS flag_one_accepted_per_cell ON ctd.flag (scan_id, variable) WHERE status = 'accepted' AND scan_id IS NOT NULL;

-- validation + review bookkeeping
CREATE OR REPLACE FUNCTION ctd.flag_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.variable <> '*' AND NOT EXISTS (SELECT 1 FROM ctd.scan_column WHERE column_name = NEW.variable) THEN
    RAISE EXCEPTION 'variable "%" is not a ctd.scan column (see ctd.scan_column) — use ''*'' for the whole row', NEW.variable;
  END IF;
  IF NEW.qual_code = 5 AND NEW.proposed_value IS NULL THEN
    RAISE EXCEPTION 'qual_code 5 (changed) needs a proposed_value';
  END IF;
  IF NEW.scan_id IS NOT NULL AND NEW.file_id IS NULL THEN
    SELECT file_id INTO NEW.file_id FROM ctd.scan WHERE scan_id = NEW.scan_id;
  END IF;
  IF TG_OP = 'INSERT' THEN
    NEW.created_by := current_user; NEW.created_at := now();
    NEW.status := 'proposed'; NEW.reviewed_by := NULL; NEW.reviewed_at := NULL;
  ELSE
    -- the target cell is fixed once proposed
    IF NEW.scan_id IS DISTINCT FROM OLD.scan_id OR NEW.file_id IS DISTINCT FROM OLD.file_id OR NEW.variable <> OLD.variable THEN
      RAISE EXCEPTION 'cannot move a flag to another scan/variable — withdraw it and propose a new one';
    END IF;
    NEW.created_by := OLD.created_by; NEW.created_at := OLD.created_at;
    IF NEW.status <> OLD.status THEN
      IF NEW.status IN ('accepted','rejected') THEN
        IF NOT pg_has_role(current_user, 'calcofi_curator', 'MEMBER') THEN
          RAISE EXCEPTION 'only calcofi_curator members may accept/reject (you can withdraw your own proposal)';
        END IF;
        NEW.reviewed_by := current_user; NEW.reviewed_at := now();
      ELSIF NEW.status = 'withdrawn' THEN
        IF OLD.created_by <> current_user AND NOT pg_has_role(current_user, 'calcofi_curator', 'MEMBER') THEN
          RAISE EXCEPTION 'only the proposer (or a curator) may withdraw';
        END IF;
      ELSIF NEW.status = 'proposed' THEN
        NEW.reviewed_by := NULL; NEW.reviewed_at := NULL;   -- re-opened by a curator
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS flag_guard ON ctd.flag;
CREATE TRIGGER flag_guard BEFORE INSERT OR UPDATE ON ctd.flag FOR EACH ROW EXECUTE FUNCTION ctd.flag_guard();

-- audit trail
CREATE TABLE IF NOT EXISTS ctd.flag_audit (
  audit_id  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  flag_id   bigint NOT NULL,
  op        text NOT NULL,
  at        timestamptz NOT NULL DEFAULT now(),
  by_role   text NOT NULL DEFAULT current_user,
  old_row   jsonb,
  new_row   jsonb
);
-- SECURITY DEFINER: the proposer has no INSERT on flag_audit (append-only by design); the owner writes it
CREATE OR REPLACE FUNCTION ctd.flag_audit_fn() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = ctd, public AS $$
BEGIN
  -- session_user = the person who logged in (inside SECURITY DEFINER current_user is the owner)
  INSERT INTO ctd.flag_audit (flag_id, op, by_role, old_row, new_row)
  VALUES (coalesce(NEW.flag_id, OLD.flag_id), TG_OP, session_user,
          CASE WHEN TG_OP <> 'INSERT' THEN to_jsonb(OLD) END,
          CASE WHEN TG_OP <> 'DELETE' THEN to_jsonb(NEW) END);
  RETURN NULL;
END $$;
DROP TRIGGER IF EXISTS flag_audit ON ctd.flag;
CREATE TRIGGER flag_audit AFTER INSERT OR UPDATE OR DELETE ON ctd.flag FOR EACH ROW EXECUTE FUNCTION ctd.flag_audit_fn();

-- row-level security: everyone reads; writers propose and edit their own open proposals; curators review
ALTER TABLE ctd.flag ENABLE ROW LEVEL SECURITY;
ALTER TABLE ctd.flag FORCE  ROW LEVEL SECURITY;   -- the owner (calcofi_admin) obeys the policies too
DROP POLICY IF EXISTS flag_read    ON ctd.flag;
DROP POLICY IF EXISTS flag_propose ON ctd.flag;
DROP POLICY IF EXISTS flag_edit_own ON ctd.flag;
DROP POLICY IF EXISTS flag_review  ON ctd.flag;
CREATE POLICY flag_read     ON ctd.flag FOR SELECT TO calcofi_reader USING (true);
CREATE POLICY flag_propose  ON ctd.flag FOR INSERT TO calcofi_writer WITH CHECK (true);
CREATE POLICY flag_edit_own ON ctd.flag FOR UPDATE TO calcofi_writer
  USING (created_by = current_user AND status = 'proposed')
  WITH CHECK (created_by = current_user AND status IN ('proposed','withdrawn'));
CREATE POLICY flag_review   ON ctd.flag FOR UPDATE TO calcofi_curator USING (true) WITH CHECK (true);

-- ── privileges ──────────────────────────────────────────────────────────────────────────────
GRANT SELECT ON ALL TABLES IN SCHEMA ctd TO calcofi_reader;
GRANT INSERT ON ctd.file, ctd.scan TO calcofi_loader;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA ctd TO calcofi_loader;
GRANT INSERT, UPDATE ON ctd.flag TO calcofi_writer;
GRANT USAGE ON SEQUENCE ctd.flag_flag_id_seq TO calcofi_writer;
REVOKE INSERT, UPDATE, DELETE ON ctd.flag_audit FROM PUBLIC, calcofi_writer, calcofi_curator;
REVOKE TRUNCATE ON ALL TABLES IN SCHEMA ctd FROM PUBLIC, calcofi_reader, calcofi_writer, calcofi_curator, calcofi_loader;

-- ── derived: best stage per study, cast headers ─────────────────────────────────────────────
CREATE OR REPLACE VIEW ctd.v_file_best AS
  SELECT f.* FROM ctd.file f WHERE f.is_best_stage;
COMMENT ON VIEW ctd.v_file_best IS 'ctd.file restricted to the best data stage available per study (final > preliminary_with_bottle > preliminary_without_bottle).';

CREATE OR REPLACE VIEW ctd.v_scan_best AS
  SELECT s.* FROM ctd.scan s JOIN ctd.file f USING (file_id) WHERE f.is_best_stage;
COMMENT ON VIEW ctd.v_scan_best IS 'ctd.scan for the best data stage per study only — what most analyses want. Superseded prelim files stay in ctd.scan for comparison.';

CREATE MATERIALIZED VIEW IF NOT EXISTS ctd.cast AS
  SELECT
    f.file_id, f.study, f.cruise_key, f.data_stage, f.cast_dir, f.is_best_stage,
    s.cast_id,
    min(s.ord_occ)        AS ord_occ,
    min(s.sta_id)         AS sta_id,
    min(s.line)           AS line,
    min(s.sta)            AS sta,
    min(s.date_time_utc)  AS datetime_utc,
    avg(s.lat_dec)        AS lat,
    avg(s.lon_dec)        AS lon,
    count(*)              AS n_scans,
    min(s.depth)          AS depth_min,
    max(s.depth)          AS depth_max,
    CASE WHEN avg(s.lon_dec) IS NOT NULL AND avg(s.lat_dec) IS NOT NULL
         THEN ST_SetSRID(ST_MakePoint(avg(s.lon_dec), avg(s.lat_dec)), 4326) END AS geom
  FROM ctd.scan s JOIN ctd.file f USING (file_id)
  GROUP BY f.file_id, f.study, f.cruise_key, f.data_stage, f.cast_dir, f.is_best_stage, s.cast_id
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS cast_pk ON ctd.cast (file_id, cast_id);
CREATE INDEX IF NOT EXISTS cast_geom_idx ON ctd.cast USING gist (geom);
COMMENT ON MATERIALIZED VIEW ctd.cast IS 'One row per cast per file, from the scan header columns (immutable by construction: derived from ctd.scan). Refresh with ctd.refresh_derived().';

-- ── generated QC views: <var>_qc / <var>_fix beside every measurement column ────────────────
-- One aggregated pivot of the ACCEPTED flags (ctd.v_flag_accepted_wide: one row per scan_id with
-- <col>_qc / <col>_fix), LEFT JOINed once onto v_scan_best. Regenerate with ctd.build_qc_views()
-- (called by ctd.refresh_derived()) if ctd.scan_column changes.
CREATE OR REPLACE FUNCTION ctd.build_qc_views() RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ctd, public AS $$
DECLARE
  mcols text[];   -- measurement + bottle columns (flaggable, fixable)
  allcols text[]; -- every scan column in ordinal order
  pivot text; qc_cols text; clean_cols text; joins text;
BEGIN
  SELECT array_agg(column_name ORDER BY ordinal) INTO mcols   FROM ctd.scan_column WHERE kind IN ('measurement','bottle');
  SELECT array_agg(column_name ORDER BY ordinal) INTO allcols FROM ctd.scan_column;
  IF mcols IS NULL THEN RAISE NOTICE 'ctd.scan_column is empty — nothing to build'; RETURN; END IF;

  SELECT string_agg(format(
           ', max(qual_code) FILTER (WHERE variable = %1$L) AS %2$I, max(proposed_value) FILTER (WHERE variable = %1$L) AS %3$I',
           c, c || '_qc', c || '_fix'), '' ORDER BY o)
    INTO pivot FROM unnest(mcols) WITH ORDINALITY AS t(c, o);
  SELECT string_agg(format(', w.%1$I, w.%2$I', c || '_qc', c || '_fix'), '' ORDER BY o)
    INTO qc_cols FROM unnest(mcols) WITH ORDINALITY AS t(c, o);
  SELECT string_agg(
           CASE WHEN c = ANY (mcols) THEN
             format(', CASE WHEN w.%2$I IS NOT NULL THEN w.%2$I WHEN coalesce(q%3$s.is_bad, false) THEN NULL ELSE s.%1$I END AS %1$I', c, c || '_fix', o)
           ELSE format(', s.%I', c) END, '' ORDER BY o)
    INTO clean_cols FROM unnest(allcols) WITH ORDINALITY AS t(c, o);
  SELECT string_agg(format(' LEFT JOIN ctd.qual_code q%1$s ON q%1$s.qual_code = w.%2$I', o, c || '_qc'), '' ORDER BY o)
    INTO joins FROM unnest(allcols) WITH ORDINALITY AS t(c, o) WHERE c = ANY (mcols);

  EXECUTE 'DROP VIEW IF EXISTS ctd.v_scan_clean';
  EXECUTE 'DROP VIEW IF EXISTS ctd.v_scan_qc';
  EXECUTE 'DROP VIEW IF EXISTS ctd.v_flag_accepted_wide';
  EXECUTE 'CREATE VIEW ctd.v_flag_accepted_wide AS SELECT scan_id' || pivot ||
          ' FROM ctd.flag WHERE status = ' || quote_literal('accepted') || ' AND scan_id IS NOT NULL GROUP BY scan_id';
  EXECUTE 'COMMENT ON VIEW ctd.v_flag_accepted_wide IS ' || quote_literal('Accepted flags pivoted to one row per scan: <col>_qc (IODE code) and <col>_fix (corrected value). Generated by ctd.build_qc_views().');
  EXECUTE 'CREATE VIEW ctd.v_scan_qc AS SELECT s.*' || qc_cols ||
          ' FROM ctd.v_scan_best s LEFT JOIN ctd.v_flag_accepted_wide w USING (scan_id)';
  EXECUTE 'COMMENT ON VIEW ctd.v_scan_qc IS ' || quote_literal('ctd.v_scan_best plus <col>_qc / <col>_fix for every measurement column, from ACCEPTED flags. Generated by ctd.build_qc_views().');
  EXECUTE 'CREATE VIEW ctd.v_scan_clean AS SELECT s.scan_id, s.file_id, s.row_num' || clean_cols ||
          ' FROM ctd.v_scan_best s LEFT JOIN ctd.v_flag_accepted_wide w USING (scan_id)' || joins;
  EXECUTE 'COMMENT ON VIEW ctd.v_scan_clean IS ' || quote_literal('ctd.v_scan_best with accepted fixes substituted and accepted is_bad flags nulled — the clean series. Generated by ctd.build_qc_views().');
  EXECUTE 'GRANT SELECT ON ctd.v_flag_accepted_wide, ctd.v_scan_qc, ctd.v_scan_clean TO calcofi_reader';
END $$;

CREATE OR REPLACE FUNCTION ctd.refresh_derived() RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ctd, public AS $$
BEGIN
  -- best-stage flags, recomputed from what is loaded (final > preliminary_with_bottle > preliminary_without_bottle).
  -- This is the one sanctioned UPDATE on ctd.file; it is a derived column, not source data.
  PERFORM set_config('ctd.allow_mutation', 'on', true);
  UPDATE ctd.file f SET is_best_stage = (f.data_stage = b.best)
  FROM (SELECT study, (array_agg(data_stage ORDER BY array_position(ARRAY['final','preliminary_with_bottle','preliminary_without_bottle'], data_stage)))[1] AS best
        FROM ctd.file GROUP BY study) b
  WHERE f.study = b.study AND f.is_best_stage IS DISTINCT FROM (f.data_stage = b.best);
  PERFORM set_config('ctd.allow_mutation', 'off', true);
  IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
             WHERE n.nspname = 'ctd' AND c.relname = 'cast' AND c.relkind = 'm' AND c.relispopulated) THEN
    REFRESH MATERIALIZED VIEW CONCURRENTLY ctd.cast;
  ELSE
    REFRESH MATERIALIZED VIEW ctd.cast;
  END IF;
  PERFORM ctd.build_qc_views();
END $$;
COMMENT ON FUNCTION ctd.refresh_derived() IS 'After a load: recompute ctd.file.is_best_stage, refresh ctd.cast, regenerate the QC views.';
GRANT EXECUTE ON FUNCTION ctd.refresh_derived() TO calcofi_loader;
GRANT EXECUTE ON FUNCTION ctd.build_qc_views() TO calcofi_loader;

RESET ROLE;
